name: Test Debug, Warning, and Error Tags

on: 
    workflow_dispatch:

jobs:
  test-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Generate debug message
        run: |
            echo "[DEBUG] This is a debug message"
            echo "::debug::This is a debug message"

      - name: Generate warning
        run: |
            echo "[WARNING] This is a warning"    
            echo "::warning::This is a warning"

      - name: Generate error
        run: |
            echo "[ERROR] This is an error"
            echo "::error::This is an error"